#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidCalc.Resource", IsApplication=true)]

namespace DroidCalc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int BackspaceTextView = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int CancelTextView = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int DecimalTextView = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int EightTextView = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int FiveTextView = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int FourTextView = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int NineTextView = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int NumberTextView = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int OKTextView = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int OneTextView = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int PeopleCountMinusTextView = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int PeopleCountPlusTextView = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int PeopleCountTextView = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int SevenTextView = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int SixTextView = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int ThreeTextView = 2131034136;
			
			// aapt resource value: 0x7f050008
			public const int TipMinusTextView = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int TipPercentMinusTextView = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int TipPercentPlusTextView = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int TipPercentTextView = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int TipPlusTextView = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int TipTextView = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int TotalPerPersonTextView = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int TotalTextView = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TotalWithTipMinusTextView = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int TotalWithTipPlusTextView = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int TotalWithTipTextView = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int TwoTextView = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int ZeroTextView = 2131034138;
			
			// aapt resource value: 0x7f05000e
			public const int captureReceiptButton = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NumberPad = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040018
			public const int Backspace = 2130968600;
			
			// aapt resource value: 0x7f040002
			public const int CameraButton = 2130968578;
			
			// aapt resource value: 0x7f040019
			public const int Cancel = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int Decimal = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int Eight = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int Five = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int Four = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int InitialAmountValue = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int InitialPeopleCount = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int MinusSign = 2130968587;
			
			// aapt resource value: 0x7f040015
			public const int Nine = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int OK = 2130968602;
			
			// aapt resource value: 0x7f04000d
			public const int One = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int PeopleCount = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int PlusSign = 2130968588;
			
			// aapt resource value: 0x7f040013
			public const int Seven = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int Six = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int Three = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int Tip = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int TipPercent = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Total = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int TotalPerPerson = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int TotalWithTip = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int Two = 2130968590;
			
			// aapt resource value: 0x7f040016
			public const int Zero = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
